services:
  checkprice:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DB_CONNECTION=${DB_CONNECTION}
      - DB_DATABASE=${DB_DATABASE}
      - DEV_ENV=${DEV_ENV}
    container_name: checkprice
    volumes:
      - ./:/var/www/html/
    ports:
      - "8080:80"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    image: checkprice
    command: /bin/bash -c "/var/www/html/scripts/setup-php.sh && php -S 0.0.0.0:80 -t /var/www/html/"
