services:
  checkprice:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: checkprice
    volumes:
      - ./:/var/www/html/
    ports:
      - "8080:80"
    environment:
      - DB_CONNECTION=${DB_CONNECTION}
      - DB_DATABASE=${DB_DATABASE}
      - DEV_ENV=${DEV_ENV}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - pythonworker

  pythonworker:
    build:
      context: .
      dockerfile: Dockerfile.python
    container_name: pythonworker
    volumes:
      - ./:/app
    working_dir: /app
    command: ["sleep", "infinity"] # sรณ pra manter vivo
