services:
  checkprice:
    build:
      context: .
      dockerfile: docker/Dockerfile
    environment:
      - DB_CONNECTION=sqlite
      - DB_DATABASE=/var/www/html/database/database.sqlite
    container_name: checkprice
    volumes:
      - ./:/var/www/html/
    ports:
      - "8080:80"
    extra_hosts:
      - "host.docker.internal:host-gateway"
      
