services:
  checkprice:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        DEV_ENV: ${DEV_ENV}
    container_name: checkprice
    ports:
      - "8080:80"
    environment:
      - DB_CONNECTION=${DB_CONNECTION}
      - DB_DATABASE=${DB_DATABASE}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - pythonworker
    volumes:
      - ./:/var/www/html/
    working_dir: /var/www/html/
  pythonworker:
    build:
      context: .
      dockerfile: Dockerfile.python
    container_name: pythonworker
    volumes:
      - ./:/var/www/html/
    working_dir: /var/www/html/
    command: ["sleep", "infinity"]
