FROM python:3.13.0-alpine

WORKDIR /app

RUN apk add --no-cache \
    build-base \
    jpeg-dev \
    zlib-dev \
    libffi-dev \
    libjpeg \
    freetype-dev \
    lcms2-dev \
    openjpeg-dev \
    tiff-dev

COPY ./python /app

COPY ./python/requirements.txt /app/requirements.txt

RUN pip install --no-cache-dir -r requirements.txt

CMD ["python", "app.py"]
